=== package-url/vers-spec/schemas/vers-type-definition.schema-1.0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "https://packageurl.org/vers-schemas/vers-type-definition.schema-1.0.json",
  "title": "VErsion Range Specifier (VERS) Type Definition",
  "description": "Schema to define the structure of a VErsion Range Specifier (VERS) type.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "$id",
    "type",
    "type_name",
    "description",
    "vers_examples"
  ],
  "properties": {
    "$schema": {
      "title": "JSON schema",
      "description": "URL of the JSON schema for VERS type definition.",
      "const": "https://packageurl.org/vers-schemas/vers-type-definition.schema-1.0.json",
      "format": "uri"
    },
    "$id": {
      "title": "VERS type definition id",
      "description": "The unique identifier URI for this VERS type definition.",
      "type": "string",
      "pattern": "^https:\\/\\/packageurl\\.org/vers-types/[a-z0-9-]+-definition\\.json$"
    },
    "type": {
      "title": "VERS type",
      "description": "The type string for this VERS type.",
      "type": "string",
      "pattern": "^[a-z][a-z0-9-\\.]+$",
      "examples": [
        "semver",
        "maven",
        "pypi",
        "npm"
      ]
    },
    "type_name": {
      "title": "Type name",
      "description": "The name of this VERS type.",
      "type": "string",
      "examples": [
        "Apache Maven Dependency Version Requirement",
        "npm version range"
      ]
    },
    "description": {
      "title": "Description",
      "description": "The description of this VERS type.",
      "type": "string",
      "examples": [
        "Apache Maven dependency version requirement as defined in a Maven POM.",
        "npm dependencies version range as defined in a package.json.",
        "RubyGems version requirement restrictions using restriction operators."
      ]
    },
    "vers_examples": {
      "title": "VERS examples",
      "description": "Examples of valid VERS notations for this VERS type.",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "pattern": "^vers:[a-z][a-z0-9-\\.]+/.*$"
      },
      "examples": [
        [
          "vers:npm/1.223",
          "vers:semver/<1.2.2|>2.0.0|=7.0.0"
        ]
      ]
    },
    "native_range_and_vers_equivalent_examples": {
      "title": "Examples of native version ranges and their VERS equivalents.",
      "description": "Optional list of examples of native version ranges mapped to their corresponding VERS syntax.",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "native_range",
          "vers"
        ],
        "properties": {
          "native_range": {
            "title": "Native range example",
            "description": "Native range example for this VERS type.",
            "type": "string"
          },
          "vers": {
            "title": "Corresponding VERS notation",
            "description": "Corresponding VERS notation for this VERS type.",
            "type": "string"
          },
          "note": {
            "title": "Note",
            "description": "Optional note about this example.",
            "type": "string"
          },
          "reference_url": {
            "title": "Reference URL",
            "description": "Optional reference URL for this native range example.",
            "type": "string",
            "format": "uri"
          }
        }
      }
    },
    "note": {
      "title": "Note",
      "description": "Note about this VERS type.",
      "type": "string"
    },
    "reference_urls": {
      "title": "Reference URLs",
      "description": "List of informational reference URLs about this VERS type, such as specifications or reference code.",
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "format": "uri"
      },
      "examples": [
        "https://maven.apache.org/pom.html#dependency-version-requirement-specification",
        "https://github.com/npm/node-semver",
        "https://docs.npmjs.com/cli/v12/configuring-npm/package-json#dependencies",
        "https://github.com/ruby/ruby/blob/d1c079751b80352d347452c8d134ffb177838adb/lib/rubygems/requirement.rb#L6"
      ]
    }
  }
}

=== package-url/vers-spec/types/npm-definition.json
{
  "$schema": "https://packageurl.org/vers-schemas/vers-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/vers-types/npm-definition.json",
  "type": "npm",
  "type_name": "npm versioning",
  "description": "npm versioning version ranges.",
  "vers_examples": [
    "vers:npm/>=1.2.0|<1.3.0",
    "vers:npm/>=1.1.0|<=2.1.0",
    "vers:npm/>=0.0.2-beta|<0.0.3",
    "vers:npm/<1.4.1|>=2.0.0|<2.17.2",
    "vers:npm/>=2.0.0-alpha8|<=2.0.0-rc2|>=2.0.0|<=2.13.0",
    "vers:npm/>=2.2.6|<2.47.0|>2.51.0|<=2.67.0",
    "vers:npm/>=1.7.0|<1.7.16|>=1.8.0|<1.8.8|>=2.0.0|<2.0.8|>=3.0.0-beta.1|<3.0.0-beta.7"
  ],
  "native_range_and_vers_equivalent_examples": [
    {
      "native_range": "^1.1.7 || >= 2.0.1",
      "vers": "vers:npm/>=1.1.7|<2.0.0|>=2.0.1"
    },
    {
      "native_range": "~1.6.5 || >=1.7.2",
      "vers": "vers:npm/>=1.6.5|<1.7.0|>=1.7.2"
    },
    {
      "native_range": "*",
      "vers": "vers:npm/*"
    },
    {
      "native_range": "2.1.4",
      "vers": "vers:npm/2.1.4"
    },
    {
      "native_range": ">=2.0.0 <=4.0.4",
      "vers": "vers:npm/>=2.0.0|<=4.0.4"
    },
    {
      "native_range": ">= 2.2.x",
      "vers": "vers:npm/>=2.2.0"
    },
    {
      "native_range": "2.0.x || 2.1.x",
      "vers": "vers:npm/>=2.0.0|<2.2.0"
    },
    {
      "native_range": "=3.0.0-rc.1",
      "vers": "vers:npm/3.0.0-rc.1"
    }
  ],
  "reference_urls": [
    "https://github.com/npm/node-semver#ranges"
  ]
}

=== package-url/vers-spec/types/pypi-definition.json
{
  "$schema": "https://packageurl.org/vers-schemas/vers-type-definition.schema-1.0.json",
  "$id": "https://packageurl.org/vers-types/pypi-definition.json",
  "type": "pypi",
  "type_name": "pypi versioning",
  "description": "pypi versioning version ranges.",
  "vers_examples": [
    "vers:pypi/<=1.3.0|3.0.0",
    "vers:pypi/>=1.0.0|<=2.0.0",
    "vers:pypi/>=3.0.0|2.0.3",
    "vers:pypi/>=3.0.0|!=2.0.3",
    "vers:pypi/0.0.2|0.0.6|>=3.0.0|0.0.1|0.0.4|0.0.5|0.0.3"
  ],
  "native_range_and_vers_equivalent_examples": [
    {
      "native_range": ">= 1.0",
      "vers": "vers:pypi/>=1.0"
    },
    {
      "native_range": "<2.1.0",
      "vers": "vers:pypi/<2.1.0"
    },
    {
      "native_range": "!=5",
      "vers": "vers:pypi/<5|>5"
    },
    {
      "native_range": ">=1.0a1,<1.0.5||>=1.1b1,<1.1.1",
      "vers": "vers:pypi/>=1.0a1|<1.0.5|>=1.1b1|<1.1.1"
    },
    {
      "native_range": ">=5.0.0,<5.0.12||>=6.0.0,<6.0.5||>=6.1.0,<6.2.2",
      "vers": "vers:pypi/>=5.0.0|<5.0.12|>=6.0.0|<6.0.5|>=6.1.0|<6.2.2"
    },
    {
      "native_range": "<21.2.3||>=22.0.0,<22.2.3||>=23.0.0,<23.0.3",
      "vers": "vers:pypi/<21.2.3|>=22.0.0|<22.2.3|>=23.0.0|<23.0.3"
    },
    {
      "native_range": "==2.3.0||==3.0.0",
      "vers": "vers:pypi/2.3.0|3.0.0"
    }
  ],
  "reference_urls": [
    "https://www.python.org/dev/peps/pep-0440/"
  ]
}
